# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

RUN pip install pip-tools

COPY ./api/requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY ./api .

# Make port 80 available to the world outside this container
EXPOSE 80

ENTRYPOINT [ "./entrypoint.sh" ]
