version: '3.8'
services:
  web:
    image: node:20
    ports:
      - "6565:3000" # 3000 is the default Next.js port
    volumes:
      - ./client:/code
      - node_modules:/code/node_modules
      - ./client/node_modules:/cache/node_modules
      - /code/.next
    working_dir: /code
    stdin_open: true
    tty: true
    command: ./entrypoint.sh
  api:
    platform: linux/x86_64
    image: sanicframework/sanic:latest-py3.10
    ports:
      - "6464:8000" # 8000 is the default Sanic port
    volumes:
      - ./api:/code
    working_dir: /code
    command: ./entrypoint.sh
    env_file:
      - ./api/.env.local

volumes:
  node_modules:
