name: Merge Staging to Main

on:
  workflow_dispatch:

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Fast-forward main
        run: |
          git merge origin/staging --ff-only
          git push origin main
